worker_processes  auto;


# Konfigurasi Load Balancer
events {
    worker_connections 10000;
}

http {
   server_tokens off;

    upstream docker-swarm {
        server 10;
        server 10;
        server 10;
        # Tambahkan server lain sesuai kebutuhan
        # Algoritma round-robin akan diterapkan secara default
    }

    server {
        listen 80;
        server_name loadbalance.com;

        location / {
            proxy_pass http://docker-swarm;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_pass_header X-My-Custom-Header; # Ganti dengan header yang spesifik jika diperlukan
        }
    }
}
