; Mengaktifkan OPcache
opcache.enable=1
opcache.enable_cli=1

; Konfigurasi dasar OPcache
opcache.memory_consumption=512
opcache.interned_strings_buffer=64
opcache.max_accelerated_files=50000
opcache.revalidate_freq=2
opcache.fast_shutdown=1