# client_body_timeout        240s;
# send_timeout               65s;
# reset_timedout_connection  on;
# keepalive_requests         10000;

server {
    listen 8080;
    client_max_body_size 80m;
    client_body_buffer_size 15m;
    index index.php index.html;
    error_log  /proc/self/fd/1;
    # access_log /var/log/nginx/access.log;
    # to boost I/O on HDD we can disable access logs
    access_log off;
    root /var/www;

    server_name  ppidphp.server.http;

    add_header X-Powered-By 'Tim IT Diskominfotik';

   # security headers
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-XSS-Protection "1; mode=block" always;
   # add_header Access-Control-Allow-Origin ${CORS_ALLOW_HOST};
   # silahkan tambahkan header csp sesuai kebutuhan aplikasi anda


    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_buffers 16 16k;               # Default: 8 4k or 8 8k
        fastcgi_buffer_size 32k;              # Default: 4k or 8k
        fastcgi_connect_timeout 60s;          # Default: 60s
        fastcgi_send_timeout 180s;            # Default: 60s
        fastcgi_read_timeout 180s;            # Default: 60s
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }


    location / {
        try_files $uri $uri/ /index.php?$query_string;
        gzip_static on;
    }

        error_page 429 /429.json;
    location = /429.json{
        add_header 'Content-Type' 'application/json charset=UTF-8';
        return 429 '{"code": "429","message": "To Many Request"}';
    }

    error_page 403 /403.json;
    location = /403.json{
        add_header 'Content-Type' 'application/json charset=UTF-8';
        return 403 '{"code": "403","message": "Forbidden / Invalid CSRF"}';
     }

    error_page 404 /404.json;
    location = /404.json{
        add_header 'Content-Type' 'application/json charset=UTF-8';
        return 404 '{"code": "404","message": "Not Found"}';
     }

    error_page 500 /500.json;
    location = /500.json{
        add_header 'Content-Type' 'application/json charset=UTF-8';
        return 500 '{"code": "500","message": "Internal Server Error"}';
    }

    error_page 502 /502.json;
    location = /502.json{
        add_header 'Content-Type' 'application/json charset=UTF-8';
        return 502 '{"code": "502","message": "Bad Gateway"}';
    }

    error_page 503 /503.json;
    location = /503.json{
        add_header 'Content-Type' 'application/json charset=UTF-8';
        return 503 '{"code": "503","message": "Service Unavailable"}';
    }

    error_page 504 /504.json;
    location = /504.json{
        add_header 'Content-Type' 'application/json charset=UTF-8';
        return 504 '{"code": "504","message": "Gateway Timeout"}';
    }
}
